name: Hello Worldb sws
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7123322449624538
title: Schock Rechtsanwälte
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#287387'
    - '#005167'
    - '#ffffff'
    - '#cedde2'
    - '#7ba8b4'
  brandStrength: 0.41032584477216005
  lightness: 0.05083478009328246
  saturation: 0.8766753415111452
  rhythmicContrast: 0.2809653193689883
purpose: []
